# Site settings
name: yerim0523
email: email
url: 
description: "A blog and a portfolio"
author: "author"
title: "Yerim's Blog"
permalink: pretty
baseurl: 

# social
github:
  username: yerim0523

twitter:
  username: username